name: full_plant_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  collection: ^1.18.0
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  intl: ^0.19.0
  page_transition: ^2.1.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    
